baseURL: "https://brinenick511.github.io/me/"
title: Haoqi Yang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Location
          url: location/
          weight: 2

params:
    # description: "Haoqi Yang's academic homepage."
    author: Haoqi Yang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Haoqi Yang
          # subtitle: "Research on efficient inference and compression for large language models."
          imageUrl: "avatar.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/

    socialIcons:
        # - name: CV
          # url: cv.pdf
        - name: Email
          url: yanghq@whu.edu.cn
        # - name: Zoom
          # url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        # - name: Office Hours
          # url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=iPVBGqoAAAAJ&hl
        # - name: GitHub
          # url: https://github.com/brinenick511
        # - name: Substack
          # url: https://pmichaillat.substack.com
        # - name: YouTube
          # url: https://www.youtube.com/@pmichaillat
        # - name: Bluesky
          # url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Haoqi Yang"
      # icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
